vc<-c(1,2,3,4,5)
charv<-c("Rajiv","Amit","Sumit","Rina","Vijay")
logicv<-c(TRUE,TRUE,FALSE,FALSE,TRUE)
list1<-list(vc,charv,logicv)
list1
class(list1)
typeof(list1)
list2<-list("Jeet","Aniket",TRUE,FALSE,54L,46,45.22)
list2
aaaaa<-c("Jeet","Aniket",TRUE,FALSE,54L,46,45.22)
aaaaa
class(aaaaa)
typeof(aaaaa)
#names of list
list3<-list(c("Sandeep","Ankit","Rajiv"),c(98,92,95),list("B.Tech","M.Sc.","CA"))
names(list3)<-c("Student","Scores","Dept")
list3
list3[1]
print(list3[1])
list3[3]
print(list3[3])
print(list3$Student)
print(list3$Dept)
#unlist  converts list into vector
listA<-list(5:10)
listA
vc1<-unlist(listA)
vc1
listB<-list(15:20)
listB
vc2<-unlist(listB)
vc2
sum1<-vc1+vc2
sum1
vc3<-c(vc1,vc2)
vc3
grp1<-list(listA,listB)
grp1
grp2<-c(listA,listB)
grp2
grp3<-list(vc1,vc2)
grp3
grp4<-c(vc1,vc2)
grp4
